### PR TITLE
Set default/optional LegalCopyright

### PR DESCRIPTION
**Pull request by mnemotiv**
This will be useful once
https://github.com/Squirrel/Squirrel.Windows/pull/430 gets merged

### CODE REVIEW

**Comment by mnemotiv** [comment]
@kevinsawicki it's merged - https://github.com/Squirrel/Squirrel.Windows/pull/430

**Comment by paulcbetts** [comment]
:+1:

**Comment by kevinsawicki** [comment]
Thanks for this

**Comment by kevinsawicki** [comment]
published in 1.0.2

**Pull request merged**
