### PR TITLE
setupIcon -> icon

### PR DESCRIPTION
**Pull request by tommoor**
Updates the icon parameter to match recent changes in Squirrel Windows. This fixes the icon on the SetupApp.exe.

We are having problems getting `Update.exe --createShortcut` to work and I'm wondering if this is related to these recent icon parameter changes - there may be something else missed somewhere?

### CODE REVIEW

**Comment by paulcbetts** [comment]
I fixed this in Squirrel 1.0.2, sorry about the dumb bug!

**Comment by tommoor** [comment]
@paulcbetts do you know if this had any affect on the createShortcut command?

**Comment by paulcbetts** [comment]
@tommoor Yeah

**Pull request closed without merging**
