### PR TITLE
Update to Squirrel.Windows 1.2.3

### LINKED ISSUE #90: Installer doesn't launch
I've created a setup.exe using grunt-electron-installer on osx, copied it to a windows machine and:

- It required installing .Net 4.5 (why?)
- After installing .Net and rebooting setup did't open, can't start install process

I use 2 npm scripts to build both windows versions:

```
"build:win": "npm run clean:win && electron-packager ./ myapp --out=dist/win --platform=win32 --arch=ia32 --version=0.35.2 --app-version 1.0.3 --app-bundle-id=myapp --helper-bundle-id=myapp --overwrite=true --asar=true --icon=assets/win/icon.ico --prune=true --ignore=dist --ignore=node_modules/\\.bin",
"build:win64": "npm run clean:win64 && electron-packager ./ myapp --out=dist/win64 --platform=win32 --arch=x64 --version=0.35.2 --app-version 1.0.3 --app-bundle-id=myapp --helper-bundle-id=myapp --overwrite=true --asar=true --icon=assets/win/icon.ico --prune=true --ignore=dist --ignore=node_modules/\\.bin"
```

And one more to call grunt-electron-installer:

```
"pack:win": "npm run build:win && npm run build:win64 && grunt create-windows-installer",
```

Here's my gruntfile with options:

```
module.exports = function(grunt) {

	grunt.loadNpmTasks('grunt-electron-installer');

	// Project configuration.
	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),
		uglify: {
			options: {
				banner: '/*! <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd") %> */\n'
			},
			build: {
				src: 'src/<%= pkg.name %>.js',
				dest: 'build/<%= pkg.name %>.min.js'
			}
		},
		'create-windows-installer': {
			x64: {
				appDirectory: 'dist/win64/myapp-win32-x64',
				outputDirectory: 'dist/win64/',
				authors: 'myapp',
				description:"myapp for desktop",
				iconUrl:"http://myiconurl.ico",
				setupIcon:"assets/win/icon.ico"
			},
			ia32: {
				appDirectory: 'dist/win/myapp-win32-ia32',
				outputDirectory: 'dist/win/',
				authors: 'myapp',
				description:"myapp for desktop",
				iconUrl:"http://myiconurl.ico",
				setupIcon:"assets/win/icon.ico"
			}
		}
	});

};
```

What's wrong? Setup didn't throw any error, just never launches.

### LINKED ISSUE #93: Installation has failed. Squirrel installation not working properly!
I can successfully build a windows installer with grunt-electron-installer, however, when I attempt to install the application with Setup.exe I get the following error:

```
Installation has failed. 

There was an error while installing the application. Check the setup log for more information and contact the author.
```

I completely emptied out: 

1. %LocalAppData%\SquirrelTemp
2. %LocalAppData%\Temp

and removed any previous installations of the app under %LocalAppData% before I executed setup.exe. There was no instance of the electron application running either. 

Upon examining %LocalAppData%, I noticed that a folder has been created for the application and all of the contents have been copied over into this folder. 

However, the SquirrelSetup.log content reports the following

```
2015-12-17 10:28:54> Program: Starting Squirrel Updater: --install .
2015-12-17 10:28:54> Program: Starting install, writing to C:\Users\myUsername\AppData\Local\SquirrelTemp
2015-12-17 10:28:54> Program: About to install to: C:\Users\myUsername\AppData\Local\accountName
2015-12-17 10:28:54> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\myUsername\AppData\Local\accountName\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2015-12-17 10:28:54> CheckForUpdateImpl: Reading RELEASES file from C:\Users\myUsername\AppData\Local\SquirrelTemp
2015-12-17 10:28:54> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-12-17 10:28:54> ApplyReleasesImpl: Writing files to app directory: C:\Users\myUsername\AppData\Local\accountName\app-1.0.0
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\content_resources_200_percent.pak to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\content_resources_200_percent.pak
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\content_shell.pak to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\content_shell.pak
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\d3dcompiler_47.dll to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\d3dcompiler_47.dll
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\accountName.exe to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\accountName.exe
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\icudtl.dat to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\icudtl.dat
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\libEGL.dll to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\libEGL.dll
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\libGLESv2.dll to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\libGLESv2.dll
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\LICENSE to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\LICENSE
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\msvcp120.dll to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\msvcp120.dll
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\natives_blob.bin to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\natives_blob.bin
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\msvcr120.dll to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\msvcr120.dll
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\node.dll to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\node.dll
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\lib\net45\pdf.dll to C:\Users\myUsername\AppData\Local\accountName\app-1.0.0\pdf.dll
2015-12-17 10:28:56> ApplyReleasesImpl: Moving file C:\Users\nna
```

Any ideas?

### PR DESCRIPTION
**Pull request by paulcbetts**
This updates to Squirrel.Windows 1.2.3, release notes at https://github.com/Squirrel/Squirrel.Windows/releases/tag/1.2.3.

Fixes #93 
Fixes #90

### CODE REVIEW

**Comment by muhammetalay** [comment]
Hi, when should we expect to see this merged?

**Comment by kevinsawicki** [comment]
Sorry for the delay in merging this, published in `1.2.1`

**Comment by paulcbetts** [comment]
@kevinsawicki np

**Comment by muhammetalay** [comment]
@kevinsawicki thanks

**Pull request merged**
